### ISSUE TITLE
First steps with Kawai

### ISSUE THREAD

**Issue by FacundoTenuta** [yukiarimo/kawai-framework#16]
Hello,
I'm exploring the Kawai framework a bit and wanted to integrate it with an Astro project [kawai-astro](https://github.com/FacundoTenuta/kawai-astro) and deploy it on vercel [deploy](https://kawai-astro.vercel.app/)
CDN didn't work.
I manually downloaded the files.
I'll keep exploring.
So far, I've relied on the documentation in docs/kawai-framework.md.
The links in the repository's Readme don't work. They link to "example.com." and
https://www.yukiarimo.tk/ don´t work.
Good job, regards.

**Comment by yukiarimo** [comment]
@FacundoTenuta, I changed Kawai's logic, and the documentation was moved to Wikis. It is still a draft, but it should be soon. You'll be able to start working on implementing Kawai. As a better reference, use the `index.html` file. It's not so bad!
